### ISSUE TITLE
Mike can you see this in your email?

### ISSUE THREAD

**Issue by nickbrazeau** [learnR-UNC/18Fall_EPID799C_RforEpi#3]
I think we want to be communicating more over "issues" to avoid the pull request discussion we had today...

P.S. Great working with you today and thanks for the Hadley video!!

**Comment by mikedolanfliss** [comment]
(Yep! Saw it in my email. Agree! I like the idea of raising issues instead of pull requests - great suggestion.) I'll close it and then let's do that!
